#!/bin/bash
#
kaivitav_kasutaja=$(whoami)

if [ "$kaivitav_kasutaja" = "root" ]; then
    if [ $# -ne 1 ]; then
        echo "Kasutusjuhend: $0 kasutajad"
    else
        kasutajad=$1
        paroolid="paroolid.txt"  # Muutke vastavalt teie kasutusele

        if [ -f "$kasutajad" -a -r "$kasutajad" -a -f "$paroolid" -a -r "$paroolid" ]; then
            echo "Failid on korras"
            while IFS=: read -r kasutajanimi
            do
                sh lisa_kasutaja "$kasutajanimi"
                parool=$(pwgen -s 8 -1)

                echo "$kasutajanimi:$parool" | chpasswd
                echo "$kasutajanimi - $parool" >> loodud_kasutajad_paroolidega
            done < "$kasutajad"
        else
            echo "Probleem failidega $kasutajad või $paroolid"
        fi
    fi
else
    echo "Sul ei ole õigust antud skripti käivitamiseks"
fi
